<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <GsPPRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\'))</GsPPRoot>
    <GsBuildRoot>$(GsPPRoot)Construction\MSBuild\$(Platform)\$(Configuration)\</GsBuildRoot>
    <OutDir>$(GsBuildRoot)Bin\</OutDir>
    <IntDir>$(GsBuildRoot)Obj\$(MSBuildProjectName)\</IntDir>
    <TargetName>$(MSBuildProjectName)</TargetName>
    <GsPython Condition="'$(GsPython)' == ''">python</GsPython>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <WarningLevel>Level4</WarningLevel>
      <ConformanceMode>true</ConformanceMode>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <AdditionalIncludeDirectories>$(GsBuildRoot)Generated;$(GsPPRoot)Compiler\include;$(GsPPRoot)SDK\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary Condition="'$(Configuration)' == 'Debug'">MultiThreadedDebugDLL</RuntimeLibrary>
      <RuntimeLibrary Condition="'$(Configuration)' != 'Debug'">MultiThreadedDLL</RuntimeLibrary>
      <Optimization Condition="'$(Configuration)' == 'Debug'">Disabled</Optimization>
      <Optimization Condition="'$(Configuration)' != 'Debug'">MaxSpeed</Optimization>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
    </ClCompile>
    <Link><SubSystem>Console</SubSystem><GenerateDebugInformation>true</GenerateDebugInformation></Link>
  </ItemDefinitionGroup>
</Project>
